name: level up

on:
  issues:
    types: [opened, closed]

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Run script
        run: |
          POINTS=4
          if [[ ${{ github.event.issue.state }} == "closed" ]]; then
            POINTS=17
          fi
          bash ./.github/workflows/scripts/make_chart.sh $POINTS

      - uses: stefanzweifel/git-auto-commit-action@v5
