name: level up

on:
  issues:
    types: [opened, closed]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run script
        run: |
          POINTS=4
          if [[ ${{ github.event.issue.status }} == "closed" ]]; then
            POINTS=17
          bash ./.github/workflows/scripts/make_chart.sh $POINTS

      - uses: stefanzweifel/git-auto-commit-action@v5
